### PR TITLE
Page action for no isolation

### LINKED ISSUE #299: Address bar icon should show red icon when isolation is disabled
It would be nice if the icon in the address bar showed the same red exclamation point as the tab bar icon, when isolation is disabled.

Reason: I use the TreeStyleTab extension for my tabs instead of the usual tab bar, so the built-in tab bar is hidden for me most of the time. I've been surprised a couple times that I had accidentally left isolation disabled for longer than I meant to, because I didn't have an obvious visual reminder.

### PR DESCRIPTION
**Pull request by louix**
New page action in the titlebar when isolation is disabled.

Resolves #299

### CODE REVIEW

**Comment by stoically** [comment]
I like the idea to have the exclamation point in the middle instead of the plus, thanks! I'd prefer if the icon color would match the [red](https://github.com/stoically/temporary-containers/blob/c724d737cae973bdadbe5d911a0d3770fd9f0ad2/src/background/browseraction.js#L94) toolbar icon badge, which is `#d90000`, what do you think?

**Comment by louix** [comment]
Thanks, you're right. It ties together well. I've updated it.

I think it looks good on the light theme, but with a dark theme `#d90000` might be a little harder to see, I'm not sure if that would be an accessibility issue. What do you think?

**Comment by stoically** [comment]
Oh, seems like I selected the wrong element the first time. The badge background is actually `#ff0000`. That's more bright and probably also looks OK for the dark theme.

Also, currently the icon doesn't change when the button in the popup is clicked or when the shortcut (<kbd>Alt</kbd>+<kbd>I</kbd>) is pressed. To achieve that it'd need a call to `pageaction.showOrHide()` [here](https://github.com/stoically/temporary-containers/blob/c724d737cae973bdadbe5d911a0d3770fd9f0ad2/src/background/preferences.js#L117) and [here](https://github.com/stoically/temporary-containers/blob/c724d737cae973bdadbe5d911a0d3770fd9f0ad2/src/background/commands.js#L109).

**Comment by louix** [comment]
Ah, that makes sense. Yep, `#ff0000` looks fine to me.

Made those changes. Thanks for the tips, I've learnt quite a lot.

**Pull request merged**
