### PR TITLE
Close leftover slack-redir.net tabs

### PR DESCRIPTION
**Pull request by Arthaey**

### CODE REVIEW

**Comment by stoically** [comment]
Thanks for the PR. Existing users wouldn't get the new array entry, so this would need additional logic in [migration.js](https://github.com/stoically/temporary-containers/blob/master/src/background/migration.js) to push it into the array for <= 1.0 users.

**Comment by stoically** [comment]
Was looking to merge this, but tested slack-redir myself, and they use a proper 302 header to redirect for me, so there's no leftover tab. t.co and AMO use meta refresh tags to redirect, that's why there's leftover tabs. Would you mind sharing your TC preferences and a test-url so I can reproduce the issue?

**Comment by stoically** [comment]
Stumbled over a meta refreshed slack-redir myself. I guess it would make sense to change the redirector tabs to be editable in the long run, like the ignore requests lists.

**Comment by Arthaey** [comment]
Thanks for taking the PR! I also only see slack-redir tabs left over _some_ of the time, not _all_ the time. I'm glad you eventually saw it do that too. :)

And yeah, probably it would be even better for users if this were a user-editable list of domains, although I understand that that will be a bit more work.

**Pull request merged**
